### ISSUE TITLE
Plugin is locale sensitive with no way to set the locale

### ISSUE THREAD

**Issue by oschwald** [oalders/code-tidyall-plugin-sortlines-naturally#1]
This makes it hard to get a stable ordering on files shared with across multiple machines. One option might be to use [Unicode::Collate](https://metacpan.org/pod/Unicode::Collate) instead of `Sort::Naturally`.

**Comment by oalders** [comment]
That seems fine to me.  Would we need to pass args to that module which would be set via the config file?  I seem to recall that this isn't easy to do with the way plugins are currently set up.  It's fine for command line args, but I'm not sure about passing other config args to be used by a plugin.

**Comment by oschwald** [comment]
Passing arguments to plugins is [pretty easy](https://github.com/houseabsolute/perl-code-tidyall/blob/master/lib/Code/TidyAll/Plugin/JSON.pm#L13), but I don't think it is necessary as long as the defaults were good.

**Comment by oalders** [comment]
Nice.  So who is making this change? :)

**Comment by oschwald** [comment]
I'll try it out and make a PR if there are no issues.
